# Generated by Django 4.0.4 on 2022-05-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studygroup', verbose_name='Группа'),
        ),
    ]
