# Generated by Django 4.0.4 on 2022-05-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='Тема')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('appearance_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата появления')),
                ('hide_test', models.BooleanField(blank=True, default=False, verbose_name='Скрыть тест')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография теста')),
                ('author_id', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('tests', models.ManyToManyField(to='main.test', verbose_name='Тесты')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата появления')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Попытка прохождения',
                'verbose_name_plural': 'Попытки прохождения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255, verbose_name='Содержание')),
                ('variant_1', models.CharField(max_length=255, verbose_name='Вариант №1')),
                ('variant_2', models.CharField(max_length=255, verbose_name='Вариант №2')),
                ('variant_3', models.CharField(max_length=255, verbose_name='Вариант №3')),
                ('variant_4', models.CharField(max_length=255, verbose_name='Вариант №4')),
                ('variant_1_is_correct', models.BooleanField(default=False, verbose_name='Варинат №1 корректен')),
                ('variant_2_is_correct', models.BooleanField(default=False, verbose_name='Варинат №2 корректен')),
                ('variant_3_is_correct', models.BooleanField(default=False, verbose_name='Варинат №3 корректен')),
                ('variant_4_is_correct', models.BooleanField(default=False, verbose_name='Варинат №4 корректен')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['id'],
            },
        ),
    ]
