# Generated by Django 4.0.4 on 2022-05-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studygroup'),
        ('main', '0002_test_group_id_delete_studygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='group_id',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.studygroup', verbose_name='Для следующих учебных групп'),
        ),
    ]
