# Generated by Django 4.0.4 on 2022-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studygroup_options'),
        ('main', '0003_alter_test_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='group_id',
            field=models.ManyToManyField(blank=True, to='accounts.studygroup', verbose_name='Для следующих учебных групп'),
        ),
    ]
