version: '3.7'
services:
  web:
    container_name: web
    hostname: web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: db
    hostname: db
    image: postgres:12.0-alpine
    restart: on-failure
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
  mongo:
    image: mongo:5.0.2
    container_name: mongo
    restart: on-failure
    hostname: mongo
    env_file:
      - ./.env.dev
    ports:
      - "27017:27017"

volumes:
  postgres_data: